spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.yaml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/user
    username: postgres
    password: postgres